[versions]
accompanist = "0.10.0"
compose = "1.0.0-beta07"
gradle = "7.0.2"
hilt = "2.35.1"
kotlin = "1.4.32"
ktlint = "0.41.0"
ktor = "1.5.4"
protobuf = "3.17.0"
retrofit = "2.9.0"
room = "2.3.0"

plugin-androidGradle = "7.0.0-beta02"
plugin-appEngine = "2.4.1"
plugin-benManesVersions = "0.38.0"
plugin-protobuf = "0.8.16"
plugin-licenses = "3.1.0"

[libraries]
# region Plugins
# TODO does not work correctly in buildscripts
#plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-androidGradle" }
#plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
#plugin-hiltAndroid = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
#plugin-appEngine = { module = "com.google.cloud.tools:appengine-gradle-plugin", version.ref = "plugin-appEngine" }
# endregion

# region App
androidx-lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.0-alpha01"
androidx-datastore = "androidx.datastore:datastore:1.0.0-beta01"
androidx-hiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:1.0.0-alpha02"

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-activity = "androidx.activity:activity-compose:1.3.0-alpha08"
compose-viewModel = "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha04"
compose-navigation = "androidx.navigation:navigation-compose:2.4.0-alpha01"

accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

timber = "com.jakewharton.timber:timber:4.7.1"
logtag-logTag = "com.cmgapps.logtag:log-tag:0.1.0"
logtag-processor = "com.cmgapps.logtag:processor:0.1.0"
# endregion

# region Misc
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.1.0"
okHttp-bom = "com.squareup.okhttp3:okhttp-bom:4.9.1"
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinxSerialization = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
cmgapps-lintLogDebug = "com.cmgapps.android:lint-logdebug:0.7.0-agp7.0"
# endregion

# region Testing
androidx-coreTesting = "androidx.arch.core:core-testing:2.1.0"
androidx-extJunit = "androidx.test.ext:junit:1.1.2"
androidx-espresso = "androidx.test.espresso:espresso-core:3.3.0"
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
junit-bom = "org.junit:junit-bom:5.7.2"
hamcrest = "org.hamcrest:hamcrest:2.2"
retrofit2-mockServer = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }
mockito-jupiter = "org.mockito:mockito-junit-jupiter:3.10.0"
kotlinx-coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.3"
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
espresso = "androidx.test.espresso:espresso-core:3.3.0"
turbine = "app.cash.turbine:turbine:0.5.1"
# endregion

# region Backend
ktor-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-servlet = { module = "io.ktor:ktor-server-servlet", version.ref = "ktor" }
ktor-html = { module = "io.ktor:ktor-html-builder", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
ktor-testing = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

logback-classic = "ch.qos.logback:logback-classic:1.2.3"
logback-gcloud = "com.google.cloud:google-cloud-logging-logback:0.120.5-alpha"
kotlinCss = "org.jetbrains:kotlin-css:1.0.0-pre.153-kotlin-1.4.32"
appEngine = "com.google.appengine:appengine:1.9.88"
# endregion


[bundles]
ktor = ["ktor-servlet", "ktor-html", "ktor-serialization"]
compose = [
  "compose-ui",
  "compose-uiTooling",
  "compose-foundation",
  "compose-material",
  "compose-materialIconsExtended",
  "compose-activity",
  "compose-viewModel",
  "compose-navigation",
]
accompanist = [
  "accompanist-insets",
  "accompanist-coil",
  "accompanist-swiperefresh",
  "accompanist-systemuicontroller"
]
androidx = [
  "androidx-lifecycleRuntimeKtx",
  "androidx-datastore",
  "androidx-hiltNavigationCompose",
]

logback = ["logback-classic", "logback-gcloud"]
