#!/bin/sh

# ln -s -f ../../scripts/pre-commit .git/hooks/pre-commit

set -e

command -v ktlint >/dev/null 2>&1 || { echo >&2 "ktlint not found.\nAborting."; exit 2; }

FILES=$(git diff --cached --name-only | grep -i -E "\.kts?" || true)

if [ -n "$FILES" ]
then
    ktlint $FILES
else
    echo "No file for ktlint"
fi

command -v swiftlint >/dev/null 2>&1 || { echo >&2 "swiftlint not found.\nAborting."; exit 2; }

FILES=$(git diff --cached --name-only | grep -i -E "\.swift" || true)

if [ -n "$FILES" ]
then
    swiftlint lint --strict $FILES
else
    echo "No file for swiftlint"
fi
