name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checkAndroid:
    runs-on: ubuntu-latest

    env:
      CV_BASE_URL: https://www.host.undefined
      CV_EMAIL: me@home.at
      CV_DEBUG_BASE_URLS: https://www.host.undefined

    steps:
      # region Setup
      - uses: actions/checkout@v2

      - name: Generate cache key
        run: ./scripts/checksum.sh checksum.txt

      - name: Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Get Kotlin version
        id: get-kotlin-version
        run: |
          echo "::set-output name=version::$(awk -F'[ ="]+' '$1 == "kotlin" { print $2 }' gradle/libs.versions.toml)"

      - name: Konan Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan
          key: konan-${{ steps.get-kotlin-version.outputs.version }}

      - name: Download dependencies
        run: ./gradlew dependencies
      # endregion
      # region Common
      - name: Check :common
        run: ./gradlew :common:check
      - name: Archive Common Test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: common-test-results
          path: |
            common/build/reports/*
            common/build/test-results/*
      # endregion
      # region App
      - name: Check :app
        run: ./gradlew :app:check
      - name: Archive App Test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: app-test-results
          path: |
            app/build/reports/*
            app/build/test-results/*
      # endregion
      # region Wearable
      - name: Check :wearable
        run: ./gradlew :wearable:check
      - name: Archive Wearable Test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: wearable-test-results
          path: |
            wearable/build/reports/*
            wearable/build/test-results/*
      # endregion
      # region Backend
      - name: Check :backend
        run: ./gradlew :backend:check
      - name: Archive Backend Test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: bff-test-results
          path: |
            backend/build/reports/*
            backend/build/test-results/*
      # endregion
      # region Desktop
      - name: Check :desktop
        run: ./gradlew :desktop:check
      - name: Archive Desktop Test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: desktop-test-results
          path: |
            desktop/build/reports/*
            desktop/build/test-results/*
      # endregion
      # region Web
      - name: Check :web
        run: ./gradlew :web:check
      - name: Archive Web Test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: web-test-results
          path: |
            web/build/reports/*
            web/build/test-results/*
      # endregion

  checkiOS:
    runs-on: macos-11

    env:
      CV_BASE_URL: https://www.host.undefined
      CV_EMAIL: me@home.at
      CV_DEBUG_BASE_URLS: https://www.host.undefined

    steps:
      # region Setup
      - uses: actions/checkout@v2
      - name: Run swiftlint
        run: |
          cd ios
          swiftlint lint
#      not working without provisioning profile -> get Apple developer account first
#      - name: Build iOS Project
#        run: |
#          xcodebuild -project ios/CurriculumVitae.xcodeproj \
#          -scheme CurriculumVitae \
#          -configuration Debug
